### PR TITLE
Add support for Puppet 6

### PR DESCRIPTION
**Pull request by mxey**
## Overview

This pull request introduces support for Puppet 6.

(Please write a summary of your pull request here. This paragraph should go into detail about what is changing, the motivation behind this change, and the approach you took.)

## Checklist

- [ ] Make sure that all of the tests pass, and fix any that don't. Just run `rake` in your checkout directory, or review the CI job triggered whenever you push to a pull request.
- [ ] Make sure that there is 100% [test coverage](https://github.com/github/octocatalog-diff/blob/master/doc/dev/coverage.md) by running `rake coverage:spec` or ignoring untestable sections of code with `# :nocov` comments. If you need help getting to 100% coverage please ask; however, don't just submit code with no tests.
- [ ] If you have added a new command line option, we would greatly appreciate a corresponding [integration test](https://github.com/github/octocatalog-diff/blob/master/doc/dev/integration-tests.md) that exercises it from start to finish. This is optional but recommended.
- [ ] If you have added any new gem dependencies, make sure those gems are licensed under the MIT or Apache 2.0 license. We cannot add any dependencies on gems licensed under GPL.
- [ ] If you have added any new gem dependencies, make sure you've checked in a copy of the `.gem` file into the [vendor/cache](https://github.com/github/octocatalog-diff/tree/master/vendor/cache) directory.

/cc [related issues] [teams and individuals, making sure to mention why you're CC-ing them]

### CODE REVIEW

**Comment by seanmil** [comment]
FYI, I started working on this as well a few days ago just before this PR was opened. I noticed it today as I was preparing my PR #226 for the same issue. I don't care which one is merged, but it would be great to get Puppet 6 support included.

**Comment by mxey** [comment]
@seanmil Yours looks a lot more comprehensive. I haven't had time yet to look into the tests since the CI does not seem to be working on this repo.

**Comment by seanmil** [comment]
> @seanmil Yours looks a lot more comprehensive. I haven't had time yet to look into the tests since the CI does not seem to be working on this repo.

It took me many hours to sort all of the testing out. The tests weren't even all passing for me before I made any changes.

**Comment by mxey** [comment]
@seanmil I am closing my PR. I have started my Puppet 6 migration using your code, so thank you :)

**Pull request closed without merging**
