### PR TITLE
Normalize file resource titles

### LINKED ISSUE #174: validate_resources seems overly strict?
> Description of problem

We've recently started running CI jobs against our puppet repo (this project is _wonderful_) - and we've noticed that `validate_resources` seems rather strict. For example, given the following puppetry, octocatalog-diff will complain that the catalog has broken references:

```
file { "/data/bar":
  ensure => directory,
}

package { "foo":
  ensure => installed,
  require => File['/data/bar/'],
}
```

The difference is the trailing slash in the name. Notably though - puppet itself does not complain when building or applying this catalog. It understands that the directory resource "/data/bar" is the same thing as "/data/bar/".

> Platform and version information

- Your OS: Linux, Debian Jessie
- Your Ruby version: 2.4.1.p111
- Your version of Puppet: 4.5.2
- Your version of octocatalog-diff: 1.5.1

> Do the tests pass from a clean checkout?

So far as I know.

> Anything else to add that you think will be helpful?

Actually - I'm more asking a question, less asking for a fix: do you believe that this is a worthwhile bug to tackle, given that puppet 5 does resource validation all on its own? If you believe it to be worthwhile and possibly not and endless wild goose chase, I'll spend an afternoon tracking this down.

### PR DESCRIPTION
**Pull request by ahayworth**
## Overview

This pull request slightly relaxes validation for (require/before/subscribe/notify) and friends on file resource types. Or rather, more closely matches puppet behavior.

We've noticed a problem at Braintree along the lines of:

```
  file { '/foo':
    ensure => directory,
  }

  file { '/bar':
    ensure => directory,
    require => File['/foo/'],
  }
```

This catalog compiles and is valid, but fails validation in octocatalog-diff.
It seems that puppet itself attempts to normalize file resource titles (and indeed
can normalize any type of resource title, given that a methodology exists in the
resource type). See:
https://github.com/puppetlabs/puppet/blob/4.10.x/lib/puppet/type/file.rb#L42

This commit attmepts to mimic that (and lifts the regex directly from the 4.10.x
branch of puppet, because it doesn't matter in puppet 5 since reference validation
is built-in).

This fixes #174 . NB - I made a mistake in the original commit message around which specific resource requirements were incorrectly flagged as invalid; this PR message is accurate.

## Checklist

- [x] Make sure that all of the tests pass, and fix any that don't. Just run `rake` in your checkout directory, or review the CI job triggered whenever you push to a pull request.
- [x] Make sure that there is 100% [test coverage](https://github.com/github/octocatalog-diff/blob/master/doc/dev/coverage.md) by running `rake coverage:spec` or ignoring untestable sections of code with `# :nocov` comments. If you need help getting to 100% coverage please ask; however, don't just submit code with no tests.

### CODE REVIEW

**Comment by ahayworth** [comment]
I'll investigate these build failures. I can't reproduce them locally but I suspect the integration tests are also not running locally...

**Comment by kpaulisse** [comment]
You can run all of the integration tests like so:

```
bundle exec rake spec:integration
```

In this case the one integration test that seems to be failing is this one:

```
bundle exec rspec ./spec/octocatalog-diff/integration/reference_validation_spec.rb

<snip>
       	Error: Syntax error at '[' at /var/folders/dw/5ftmkqk972j_kw2fdjyzdqdw0000gn/T/ocd-ipc-20180213-36294-3s4mls/ocd-builddir-20180213-36530-b1y7eg/environments/production/modules/test/manifests/file_tests.pp:8:21 on node rspec-node.github.net
       	Error: Syntax error at '[' at /var/folders/dw/5ftmkqk972j_kw2fdjyzdqdw0000gn/T/ocd-ipc-20180213-36294-3s4mls/ocd-builddir-20180213-36530-b1y7eg/environments/production/modules/test/manifests/file_tests.pp:8:21 on node rspec-node.github.net
       	Error: Failed to compile catalog for node rspec-node.github.net: Syntax error at '[' at /var/folders/dw/5ftmkqk972j_kw2fdjyzdqdw0000gn/T/ocd-ipc-20180213-36294-3s4mls/ocd-builddir-20180213-36530-b1y7eg/environments/production/modules/test/manifests/file_tests.pp:8:21 on node rspec-node.github.net
```

It looks like Puppet doesn't like the space between `File` and `['/foo']` in the fixture, `./spec/octocatalog-diff/fixtures/repos/reference-validation/modules/test/manifests/file_tests.pp`.

**Comment by ahayworth** [comment]
It's days like these that I'm reminded that I'm really not an app developer anymore. ^_^

Integration tests passed locally after fixing that spacing issue and you know, actually running them - I've squashed the fixes and hopefully the builds pass in CI this time around. :)

**Comment by kpaulisse** [comment]
Hey @ahayworth great news -- it looks like CI is passing now. 😸 👍 

Are you finished working on this now, and ready for me to put it through our normal pre-release testing? Or do you still have additional work before we test it?

**Comment by ahayworth** [comment]
As far as I know, it’s done. This solves the problems we were seeing in our env. Test away! 😁

- Andrew Hayworth

**Comment by kpaulisse** [comment]
I've merged this into https://github.com/github/octocatalog-diff/pull/180 so my current plan is to test https://github.com/github/octocatalog-diff/pull/180 internally at GitHub and then once that is 👍 merge both at the same time.

**Comment by ahayworth** [comment]
Sounds great, thank you!

- Andrew Hayworth

**Pull request merged**
